package com.pronskiy.agenstorm.commit.llm

import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

/**
 * In-memory backend: emits [chunks] with a small delay between them so streaming is visible, then fails with
 * [failure] when one is configured. Used by tests and selectable as backend `fake` to exercise the whole
 * pipeline without a network or an API key.
 */
class FakeBackend(
    private val chunks: List<String> = DEFAULT_CHUNKS,
    private val delayMs: Long = 150,
    private val failure: String? = null,
) : LlmBackend {

    override val id: String = ID

    override fun stream(request: LlmRequest): Flow<String> = flow {
        for (chunk in chunks) {
            if (delayMs > 0) delay(delayMs)
            emit(chunk)
        }
        if (failure != null) throw LlmException(failure)
    }

    override suspend fun validate(): String? = failure

    companion object {
        const val ID = "fake"

        val DEFAULT_CHUNKS: List<String> = listOf(
            "feat(demo): ",
            "stream a fake commit message\n",
            "\nGenerated by the Agenstorm fake backend ",
            "to exercise the pipeline without a network.",
        )
    }
}
