package com.pronskiy.agenstorm.commit

import com.intellij.icons.AllIcons
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.actionSystem.DataContext
import com.intellij.openapi.actionSystem.impl.SimpleDataContext
import com.intellij.openapi.components.service
import com.intellij.openapi.vcs.FilePath
import com.intellij.openapi.vcs.LocalFilePath
import com.intellij.openapi.vcs.VcsDataKeys
import com.intellij.openapi.vcs.changes.Change
import com.intellij.openapi.vcs.changes.SimpleContentRevision
import com.intellij.openapi.vcs.ui.CommitMessage
import com.intellij.testFramework.TestActionEvent
import com.intellij.testFramework.fixtures.BasePlatformTestCase
import com.intellij.util.ui.UIUtil
import com.intellij.vcs.commit.CommitWorkflowUi
import com.pronskiy.agenstorm.core.AgenstormSettings
import java.lang.reflect.Proxy

/**
 * Step D1.6: the action's update() logic (visibility, enablement, run/stop presentation) and a full run through
 * actionPerformed() with the fake backend selected in the settings. The commit UI is a dynamic proxy that
 * only answers the two "included" queries the action uses.
 */
class GenerateCommitMessageActionTest : BasePlatformTestCase() {

    private lateinit var commitMessage: CommitMessage
    private val action = GenerateCommitMessageAction()

    override fun setUp() {
        super.setUp()
        commitMessage = CommitMessage(project)
        AgenstormSettings.getInstance().loadState(AgenstormSettings.State(commitBackendId = "fake"))
    }

    override fun tearDown() {
        try {
            AgenstormSettings.getInstance().loadState(AgenstormSettings.State())
            commitMessage.dispose()
        } finally {
            super.tearDown()
        }
    }

    fun testHiddenOutsideTheCommitUiAndWhenTheFeatureIsOff() {
        val noCommitUi = SimpleDataContext.builder().add(CommonDataKeys.PROJECT, project).build()
        assertFalse(update(noCommitUi).isVisible)

        AgenstormSettings.getInstance().loadState(AgenstormSettings.State(commitEnabled = false, commitBackendId = "fake"))
        assertFalse(update(commitContext(listOf(change()))).isVisible)
    }

    fun testDisabledWhileNoKnownBackendIsConfigured() {
        AgenstormSettings.getInstance().loadState(AgenstormSettings.State(commitBackendId = "nope"))
        val presentation = update(commitContext(listOf(change())))
        assertTrue(presentation.isVisible)
        assertFalse(presentation.isEnabled)
    }

    fun testGeneratesIntoTheMessageFieldAndTogglesToStopWhileRunning() {
        val context = commitContext(listOf(change()))
        val idle = update(context)
        assertTrue(idle.isEnabledAndVisible)
        assertSame(AllIcons.Actions.Lightning, idle.icon)

        action.actionPerformed(TestActionEvent.createTestEvent(action, context))
        val service = project.service<CommitGenerationService>()
        assertTrue(service.isRunning)
        assertSame(AllIcons.Run.Stop, update(context).icon)

        awaitUntil { !service.isRunning }
        assertEquals("feat(demo): stream a fake commit message\n\nGenerated by the Agenstorm fake backend to exercise the pipeline without\na network.", commitMessage.text)
        assertSame(AllIcons.Actions.Lightning, update(context).icon)
    }

    fun testSecondClickCancelsTheRunningGeneration() {
        val context = commitContext(listOf(change()))
        action.actionPerformed(TestActionEvent.createTestEvent(action, context))
        val service = project.service<CommitGenerationService>()
        assertTrue(service.isRunning)

        action.actionPerformed(TestActionEvent.createTestEvent(action, context))
        awaitUntil { !service.isRunning }

        assertFalse(commitMessage.text.contains("without a network"))
    }

    fun testNothingIncludedDoesNotStartAGeneration() {
        action.actionPerformed(TestActionEvent.createTestEvent(action, commitContext(emptyList())))
        assertFalse(project.service<CommitGenerationService>().isRunning)
        assertEquals("", commitMessage.text)
    }

    private fun update(context: DataContext) = TestActionEvent.createTestEvent(action, context).also { action.update(it) }.presentation

    private fun commitContext(changes: List<Change>): DataContext = SimpleDataContext.builder()
        .add(CommonDataKeys.PROJECT, project)
        .add(VcsDataKeys.COMMIT_WORKFLOW_UI, commitUi(changes))
        .add(VcsDataKeys.COMMIT_MESSAGE_CONTROL, commitMessage)
        .build()

    private fun commitUi(changes: List<Change>): CommitWorkflowUi =
        Proxy.newProxyInstance(javaClass.classLoader, arrayOf(CommitWorkflowUi::class.java)) { _, method, _ ->
            when (method.name) {
                "getIncludedChanges" -> changes
                "getIncludedUnversionedFiles" -> emptyList<FilePath>()
                "dispose" -> null
                "hashCode" -> 0
                "equals" -> false
                "toString" -> "CommitWorkflowUi stub"
                else -> throw UnsupportedOperationException(method.name)
            }
        } as CommitWorkflowUi

    private fun change(): Change {
        val path = LocalFilePath(project.basePath + "/src/Foo.php", false)
        return Change(SimpleContentRevision("<?php\na\n", path, "HEAD"), SimpleContentRevision("<?php\nb\n", path, "WORKING"))
    }

    private fun awaitUntil(condition: () -> Boolean) {
        val deadline = System.currentTimeMillis() + 20_000
        while (!condition()) {
            assertTrue("timed out waiting", System.currentTimeMillis() < deadline)
            UIUtil.dispatchAllInvocationEvents()
            Thread.sleep(10)
        }
    }
}
