#!/bin/sh
# Generated by Agenstorm — do not edit, this file is rewritten whenever the plugin changes it.
# This is what $EDITOR and $VISUAL point at inside IDE terminals. It hands the file to the IDE window the
# terminal belongs to and blocks until that tab is closed, which is the contract every caller of $EDITOR
# already expects: `git commit`, `crontab -e`, and Claude Code's Ctrl+G, which reads the file back the
# moment this process exits and would take the text back unchanged if we returned any earlier.
# POSIX sh only: the same file is named by $EDITOR for zsh, bash and fish.
#
# The port and token variables are the `open` shim's — one endpoint per project serves both.

fallback() {
	# The IDE cannot take it. Hand over to whatever this terminal would have used without us, which the
	# IDE captured from the login shell before the shim replaced it.
	# Unquoted on purpose: $EDITOR has always been a command line, not a file name.
	if [ -n "$AGENSTORM_EDITOR_FALLBACK" ]; then
		exec $AGENSTORM_EDITOR_FALLBACK "$@"
	fi
	for editor in vi vim nano; do
		if command -v "$editor" >/dev/null 2>&1; then
			exec "$editor" "$@"
		fi
	done
	echo "${0##*/}: no editor to fall back on" >&2
	exit 127
}

[ -n "$AGENSTORM_OPEN_PORT" ] || fallback "$@"   # not an Agenstorm terminal
[ $# -gt 0 ] || fallback "$@"                    # nothing to edit
command -v curl >/dev/null 2>&1 || fallback "$@"

# NUL-separated so a path may hold spaces, quotes or newlines without any encoding. The token is the first
# field of the body and never a curl argument — see open.sh for why that matters on Linux.
# Nothing bounds the wait itself: the answer comes when the tab closes, and that is the user's own pace.
# The connect timeout still bounds the one part that could hang with nobody watching.
printf '%s\0' "$AGENSTORM_OPEN_TOKEN" "$PWD" "$@" |
	curl -fsS --connect-timeout 2 -X POST --data-binary @- \
		"http://127.0.0.1:$AGENSTORM_OPEN_PORT/edit" >/dev/null 2>&1 && exit 0

fallback "$@"  # 409 (the IDE declined), 403, or the IDE is gone
