#!/bin/sh
# Generated by Agenstorm — do not edit, this file is rewritten whenever the plugin changes it.
# It shadows `open` inside IDE terminals only. Anything it does not claim goes to the real `open`,
# which keeps its own flags, its own URL handling and its own error messages.
# POSIX sh only: the same file is on PATH for zsh, bash and fish.

real=/usr/bin/open
if [ ! -x "$real" ]; then
	real=$(command -v xdg-open 2>/dev/null) || real=
	# Never exec ourselves: on Linux the shim may be installed under the name it just found.
	case "$real" in "${0%/*}"/*) real= ;; esac
fi

fallback() {
	[ -n "$real" ] && exec "$real" "$@"
	echo "${0##*/}: command not found" >&2
	exit 127
}

[ -n "$AGENSTORM_OPEN_PORT" ] || fallback "$@"  # not an Agenstorm terminal
[ $# -gt 0 ] || fallback "$@"                   # no arguments: macOS prints its usage
case "$1" in -*|*://*) fallback "$@" ;; esac    # flags and URLs are macOS's job
command -v curl >/dev/null 2>&1 || fallback "$@"

# NUL-separated so a path may hold spaces, quotes or newlines without any encoding.
# The token is a header, never an argument: `ps` must not be able to read it.
printf '%s\0' "$PWD" "$@" |
	curl -fsS -m 2 -X POST --data-binary @- \
		-H "X-Agenstorm-Token: $AGENSTORM_OPEN_TOKEN" \
		"http://127.0.0.1:$AGENSTORM_OPEN_PORT/open" >/dev/null 2>&1 && exit 0

fallback "$@"  # 409 (the IDE declined), 403, a timeout, or the IDE is gone
